# Generated by Django 3.2 on 2022-08-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DEVELOPER', 'Developer'), ('TRADER', 'Trader'), ('INVESTOR', 'Inventor')], max_length=50),
        ),
    ]
