# Generated by Django 3.2 on 2022-11-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('TRADER', 'Trader'), ('INVESTOR', 'Investor')], default='DEVELOPER', max_length=20),
            preserve_default=False,
        ),
    ]
