# Generated by Django 3.2 on 2022-11-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('TRADER', 'Trader'), ('INVESTOR', 'Investor'), ('ADMIN', 'Admin')], default='DEVELOPER', max_length=20),
        ),
    ]
