# Generated by Django 3.2 on 2022-10-08 13:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220806_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MODERATOR', 'moderator'), ('DEVELOPER', 'Developer'), ('TRADER', 'Trader'), ('INVESTOR', 'Investor')], max_length=50),
        ),
    ]
