# Generated by Django 3.2 on 2022-10-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20221008_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmed_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='usage',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('BUSINESS', 'Business'), ('PERSONAL', 'Personal')], default='PERSONAL', max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DEVELOPER', 'Developer'), ('TRADER', 'Trader'), ('INVESTOR', 'Investor')], max_length=55),
        ),
    ]
