# Generated by Django 3.2 on 2022-10-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20221029_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmed_email',
            new_name='is_confirmed',
        ),
    ]
