# Generated by Django 3.2 on 2022-06-25 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('ticker', models.CharField(max_length=10)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prev_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['change'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('ticker', models.CharField(max_length=10)),
                ('volume', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prev_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('last_update_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='stocks_v1.stock')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical stock',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
