# Generated by Django 3.2 on 2022-06-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0002_auto_20220625_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='volume',
            field=models.PositiveIntegerField(default=1.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.PositiveIntegerField(default=1.0),
        ),
    ]
