# Generated by Django 3.2 on 2022-10-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0003_alter_tracker_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='quote',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=10),
            preserve_default=False,
        ),
    ]
