# Generated by Django 3.2 on 2022-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0003_auto_20220625_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='volume',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
