# Generated by Django 3.2 on 2022-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0004_tracker_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='track_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
