# Generated by Django 3.2 on 2022-10-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0005_alter_tracker_track_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='track_price',
        ),
        migrations.AddField(
            model_name='tracker',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
