# Generated by Django 3.2 on 2022-07-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0006_auto_20220721_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='ticker',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
