# Generated by Django 3.2 on 2022-10-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0006_auto_20221001_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='current_price',
            new_name='at_tracking',
        ),
    ]
