# Generated by Django 3.2 on 2022-10-05 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks_v1', '0007_rename_current_price_tracker_at_tracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='quote',
            new_name='quote_price',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='investor',
        ),
        migrations.AddField(
            model_name='tracker',
            name='investors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
