# Generated by Django 3.2 on 2022-10-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0008_auto_20221005_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='in_queue',
            new_name='matched',
        ),
    ]
