# Generated by Django 3.2 on 2022-10-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0009_rename_in_queue_tracker_matched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='completed',
            new_name='matched_date',
        ),
    ]
