# Generated by Django 3.2 on 2022-10-05 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks_v1', '0012_auto_20221005_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.CharField(default='genesis', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='viewers',
            field=models.ManyToManyField(related_name='viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
