# Generated by Django 3.2 on 2022-10-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0013_auto_20221005_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipients',
        ),
        migrations.AddField(
            model_name='notification',
            name='subscribers',
            field=models.ManyToManyField(related_name='recipients', to='stocks_v1.Tracker'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='matched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
