# Generated by Django 3.2 on 2022-10-07 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0014_auto_20221007_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='notification',
            name='subscribers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='stocks_v1.tracker'),
        ),
    ]
