# Generated by Django 3.2 on 2022-10-07 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0016_auto_20221007_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='stocks_v1.stock'),
        ),
    ]
