# Generated by Django 3.2 on 2022-10-07 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks_v1', '0017_alter_tracker_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='investors',
            field=models.ManyToManyField(related_name='trackers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='stocks_v1.stock'),
        ),
    ]
