# Generated by Django 3.2 on 2022-11-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0019_auto_20221007_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstock',
            old_name='prev_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='prev_price',
            new_name='close',
        ),
    ]
