# Generated by Django 3.2 on 2022-11-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0020_auto_20221122_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstock',
            old_name='open_price',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='open_price',
            new_name='open',
        ),
    ]
