# Generated by Django 3.2 on 2022-11-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_v1', '0023_auto_20221122_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstock',
            old_name='min_price',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='min_price',
            new_name='low',
        ),
    ]
