# Generated by Django 3.2 on 2022-11-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstock',
            name='prev',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='prev',
        ),
    ]
